### ISSUE TITLE
BRDF Fallback Geometry inconsistency

### ISSUE THREAD

**Issue by ASVincent** [OpenDataCubePipelines/swfo#31]
When evaluating Polygon region calculated by the brdf_fallback I noticed an inconsistency in the spatial region returned. The simplest answer I can think of is that I have have incorrectly initialised the Affine values for the spatial transform from pixel values to spatial values.

For a dataset equivalent to the horizontal tile 29 and vertical tile 12 I observed the following values:
Fallback Metadata

> ...
>              type: Polygon
>              coordinates:
>              - - - 0.0
>                  - -463.3127165279167
>                - - 1111950.5196669996
>                  - -463.3127165279167
>                - - 11771886249.134043
>                  - -3210211635.662179
>                - - 26108251334.99249
>                  - -7120199528.38847
>                - - 28714072039.160404
>                  - -7830893194.7527685
>                - - 29341988469.709778
>                  - -8002148098.06625
>                - - 29356273307.550964
>                  - -8006044204.912716
>                - - 29355493719.1992
>                  - -8006044204.912716
>                - - 0.0
>                  - -463.3127165279167
> ...

Definitive Metadata:

> ...
>            geometry:
>              type: Polygon
>              coordinates:
>              - - - 12231455.716333
>                  - -3335851.559
>                - - 12231455.716333
>                  - -4447802.078667
>                - - 12677783.285170192
>                  - -4447802.078667
>                - - 13220835.5658659
>                  - -4191077.9204856046
>                - - 13322325.027612118
>                  - -4133150.9486327153
>                - - 13343406.236
>                  - -4116197.9300964945
>                - - 13343406.236
>                  - -3335851.559
>                - - 12231455.716333
>                  - -3335851.559
> ...

The only other observation I had when evaluating the sample fallback generation was that the compression and filter opts weren't configured to the acceptance criteria.

**Comment by passangd** [comment]
This has been resolved, issue was passing geo-transform parameters directly into Affine without indicating it was from gdal.

**Comment by sixy6e** [comment]
Fixed via #32
